--liquibase formatted sql

--changeset makarov:1
CREATE TABLE faculty(
   id bigint generated by default as IDENTITY primary key,
   name varchar(255),
   color varchar(255)
);

CREATE TABLE student(
                        id          bigint generated by default as IDENTITY primary key,
                        name        varchar(255),
                        age         int,
                        faculty_id  bigint,
                        FOREIGN KEY (faculty_id) REFERENCES faculty (id)
);

CREATE TABLE avatar (
                        id          bigint generated by default as IDENTITY primary key,
                        file_size   bigint,
                        media_type  varchar(255),
                        file_path   varchar(255),
                        student_id  bigint,
                        data        oid,
                        FOREIGN KEY (student_id) REFERENCES student (id)
);

--changeset makarov:2
ALTER TABLE faculty
    ADD CONSTRAINT unique_name UNIQUE (name);

ALTER TABLE student ADD CHECK ( age > 16 );